apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maana-lp-service-db-claim
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: default
